<div class="content-header">
    <?php echo $this->getHeaderHtml() ?>
    <p class="form-buttons"><?php echo $this->getButtonsHtml('header') ?></p>
</div>

<?php if ($message = $this->getMessage()) : ?>
    <div class="notification-global"><?php echo $message ?></div>

<?php endif; ?>


<div class="">

  <table>
    <tr>
      <td style="padding-right:30px;border-right:solid #dfdfdf;"><h3>Configurações do plugin:</h3>
      <form class="" action="<?php echo $this->getUrl("admin_envio/adminhtml_index/salvaconf") ?>" method="post">


        <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />


        <label for="">Mostrar frete para o cliente?</label> <br>
          <select class="" name="show_in_front">
            <option value="1">Mostrar valor</option>
            <option value="0">Não mostrar valor</option>
          </select>
           <br> <br> <br>

        <label for="">Definir porcetagem de lucro sobre o frete:</label> <br>
          <input type="text" name="profit_value" value="<?php echo $this->getProfit(); ?>">
          <br> <br> <br>

          <label for="">Definir dias extras para envio:</label> <br>
          <input type="text" name="profit_days" value="<?php echo $this->getProfit_Days(); ?>">
          <br> <br> <br>

        <label for="">Utilizar declaração de valor?</label> <br>
          <select class="" name="value_declaration">
              <option value="0">Não usar declaração de valor.</option>
              <option value="1">Usar declaração de valor.</option>
          </select> <br> <br> <br>

        <label for="">Entrega de mão própria?</label> <br>
          <select class="" name="own_hand">
            <option value="0">Não usar mão própria.</option>
            <option value="1">Usar mão própria.</option>
          </select> <br> <br> <br>

        <label for="">Aviso de recebimento?</label> <br>
          <select class="" name="receipt">
            <option value="0">Não exigir aviso de recebimento.</option>
            <option value="1">Exigir aviso de recebimento.</option>
          </select> <br> <br> <br>




    <?php $saved = $this->getSaved();?>

      <h3>Escolha as suas transportadoras:</h3>
      <?php $transportadoras = $this->getTransportadoras();?>

      <?php foreach ($transportadoras as $transportadora): ?>
        <label>
        <input type="checkbox" name="<?php echo $transportadora->name;?>" value="<?php echo $transportadora->name;?>" <?php if($saved[str_replace(" ","_",$transportadora->name)] == $transportadora->name){ echo "checked='checked'";} ?> >
         <?php echo $transportadora->name;?> </label>

        <br><br>

          <?php endforeach; ?>
            <button type="submit" name="button">Salvar Configurações</button>
      </form>

      </td>
      <td style="padding-left:60px">
        <h3>Dados do Remetente:</h3>

        <form class="" action="<?php echo $this->getUrl("admin_envio/adminhtml_index/salvaremetente")?>" method="post">
          <label for="">E-mail :<?php echo $this->getEmail();?> </label><br><br>

          <label for="">CEP</label><br>
          <input type="text" name="cep" value="<?php echo $this->getEndereco()->cep;?> "> <br><br>

          <label for="">Endereço</label><br>
          <input type="text" name="address" value="<?php echo $this->getEndereco()->address;?>"><br><br>

          <label for="">Numero</label><br>
          <input type="text" name="number" value="<?php echo $this->getEndereco()->number;?>"><br><br>

          <label for="">Bairro</label><br>
          <input type="text" name="district" value="<?php echo $this->getEndereco()->district;?>"><br><br>

          <label for="">Cidade</label><br>
          <input type="text" name="city" value="<?php echo $this->getEndereco()->city;?>"><br><br>

          <label for="">UF</label><br>
          <input type="text" name="uf" value="<?php echo $this->getEndereco()->uf;?>"><br><br>

          <button type="submit" name="button">Salvar Remetente</button>

          <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
        </form>
      </td>
    </tr>
  </table>



</div>
